echo delete frontend deployment and service...
kubectl -n default delete deployment todolistapp-springboot-deployment --ignore-not-found
kubectl -n default delete service todolistapp-springboot-service --ignore-not-found