-- =====================================================================
-- 02_add_vector_columns.sql
-- Agrega columna EMBEDDING (VECTOR) e indices vectoriales a las tablas
-- que se haran buscables semanticamente. Ejecutar como ADMIN.
-- Dimension 384 = salida de ALL_MINILM_L12_V2.
-- =====================================================================

ALTER TABLE ADMIN.PROYECTOS      ADD (EMBEDDING VECTOR(384, FLOAT32));
ALTER TABLE ADMIN.SPRINTS        ADD (EMBEDDING VECTOR(384, FLOAT32));
ALTER TABLE ADMIN.TAREAS         ADD (EMBEDDING VECTOR(384, FLOAT32));
ALTER TABLE ADMIN.KPIS           ADD (EMBEDDING VECTOR(384, FLOAT32));
ALTER TABLE ADMIN.USUARIOS       ADD (EMBEDDING VECTOR(384, FLOAT32));
ALTER TABLE ADMIN.TAREA_HISTORIAL ADD (EMBEDDING VECTOR(384, FLOAT32));

-- Indices vectoriales (HNSW en memoria, distancia coseno)
CREATE VECTOR INDEX proyectos_embedding_idx ON ADMIN.PROYECTOS (EMBEDDING)
    ORGANIZATION INMEMORY NEIGHBOR GRAPH
    DISTANCE COSINE
    WITH TARGET ACCURACY 95;

CREATE VECTOR INDEX sprints_embedding_idx ON ADMIN.SPRINTS (EMBEDDING)
    ORGANIZATION INMEMORY NEIGHBOR GRAPH
    DISTANCE COSINE
    WITH TARGET ACCURACY 95;

CREATE VECTOR INDEX tareas_embedding_idx ON ADMIN.TAREAS (EMBEDDING)
    ORGANIZATION INMEMORY NEIGHBOR GRAPH
    DISTANCE COSINE
    WITH TARGET ACCURACY 95;

CREATE VECTOR INDEX kpis_embedding_idx ON ADMIN.KPIS (EMBEDDING)
    ORGANIZATION INMEMORY NEIGHBOR GRAPH
    DISTANCE COSINE
    WITH TARGET ACCURACY 95;

CREATE VECTOR INDEX usuarios_embedding_idx ON ADMIN.USUARIOS (EMBEDDING)
    ORGANIZATION INMEMORY NEIGHBOR GRAPH
    DISTANCE COSINE
    WITH TARGET ACCURACY 95;

CREATE VECTOR INDEX historial_embedding_idx ON ADMIN.TAREA_HISTORIAL (EMBEDDING)
    ORGANIZATION INMEMORY NEIGHBOR GRAPH
    DISTANCE COSINE
    WITH TARGET ACCURACY 95;
