-- =====================================================================
-- 01_seed_sprints_tareas.sql
-- Inserta Sprints 0-3 y ~13 tareas por sprint (proyecto 1).
-- Usa WHERE NOT EXISTS para no duplicar si ya existen, y hace COMMIT
-- despues de cada bloque.
-- =====================================================================

-- ---------------------------------------------------------------
-- 1) SPRINTS 0-3
-- ---------------------------------------------------------------
INSERT INTO ADMIN.SPRINTS (SPRINT_ID, NOMBRE, FECHA_INICIO, FECHA_FIN, ESTATUS, OBJETIVO, PROYECTO_ID)
SELECT 10, 'Sprint 0 - Fundacion e infraestructura', DATE '2026-02-18', DATE '2026-03-04', 'Completado',
       'Configurar repositorios, infraestructura en OCI, base de datos y proyectos base de backend, frontend y bot de Telegram.', 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.SPRINTS WHERE SPRINT_ID = 10);
COMMIT;

INSERT INTO ADMIN.SPRINTS (SPRINT_ID, NOMBRE, FECHA_INICIO, FECHA_FIN, ESTATUS, OBJETIVO, PROYECTO_ID)
SELECT 11, 'Sprint 1 - Autenticacion y CRUD base', DATE '2026-03-05', DATE '2026-03-25', 'Completado',
       'Implementar autenticacion, CRUD de proyectos/sprints/tareas y las vistas principales del portal y del bot.', 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.SPRINTS WHERE SPRINT_ID = 11);
COMMIT;

INSERT INTO ADMIN.SPRINTS (SPRINT_ID, NOMBRE, FECHA_INICIO, FECHA_FIN, ESTATUS, OBJETIVO, PROYECTO_ID)
SELECT 12, 'Sprint 2 - KPIs, historial y reportes', DATE '2026-03-26', DATE '2026-04-22', 'Completado',
       'Agregar el modulo de KPIs, historial de cambios, dashboards y reportes del proyecto.', 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.SPRINTS WHERE SPRINT_ID = 12);
COMMIT;

INSERT INTO ADMIN.SPRINTS (SPRINT_ID, NOMBRE, FECHA_INICIO, FECHA_FIN, ESTATUS, OBJETIVO, PROYECTO_ID)
SELECT 13, 'Sprint 3 - IA, busqueda semantica y pruebas de carga', DATE '2026-04-23', DATE '2026-06-10', 'Activo',
       'Integrar busqueda semantica con Oracle AI Vector Search, asistente de IA con Groq y validar el sistema con pruebas de carga.', 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.SPRINTS WHERE SPRINT_ID = 13);
COMMIT;

-- ---------------------------------------------------------------
-- 2) TAREAS POR SPRINT (~13 cada uno)
-- ---------------------------------------------------------------
-- Sprint 0: Sprint 0 - Fundacion e infraestructura
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1001, 'Configurar repositorio y estructura del monorepo', 'Alta', 'Completado',
       DATE '2026-02-18', DATE '2026-02-21',
       'Configurar repositorio y estructura del monorepo.', 4, 2, 2, 0, 10, 1, 2, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1001);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1002, 'Setup del proyecto Spring Boot con Maven', 'Media', 'Completado',
       DATE '2026-02-19', DATE '2026-02-23',
       'Setup del proyecto Spring Boot con Maven.', 5, 6, 3, 0, 10, 1, 3, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1002);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1003, 'Configurar conexion a Oracle Autonomous DB (wallet)', 'Baja', 'Completado',
       DATE '2026-02-20', DATE '2026-02-25',
       'Configurar conexion a Oracle Autonomous DB (wallet).', 6, 5, 4, 0, 10, 1, 4, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1003);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1004, 'Diseno del modelo de datos (diagrama ER)', 'Alta', 'Completado',
       DATE '2026-02-21', DATE '2026-02-27',
       'Diseno del modelo de datos (diagrama ER).', 7, 9, 5, 0, 10, 1, 2, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1004);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1005, 'Crear esquema de tablas USUARIOS, PROYECTOS y SPRINTS', 'Media', 'Completado',
       DATE '2026-02-22', DATE '2026-03-01',
       'Crear esquema de tablas USUARIOS, PROYECTOS y SPRINTS.', 8, 9, 6, 0, 10, 1, 3, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1005);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1006, 'Crear esquema de tablas TAREAS, KPIS y TAREA_HISTORIAL', 'Baja', 'Completado',
       DATE '2026-02-23', DATE '2026-02-26',
       'Crear esquema de tablas TAREAS, KPIS y TAREA_HISTORIAL.', 9, 7, 7, 0, 10, 1, 4, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1006);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1007, 'Setup del portal web en React con Vite', 'Alta', 'Completado',
       DATE '2026-02-24', DATE '2026-02-28',
       'Setup del portal web en React con Vite.', 10, 11, 8, 0, 10, 1, 2, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1007);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1008, 'Configurar enrutamiento y layout base del portal', 'Media', 'Completado',
       DATE '2026-02-25', DATE '2026-03-02',
       'Configurar enrutamiento y layout base del portal.', 4, 3, 2, 0, 10, 1, 3, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1008);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1009, 'Implementar endpoint de health check', 'Baja', 'Completado',
       DATE '2026-02-26', DATE '2026-03-04',
       'Implementar endpoint de health check.', 5, 7, 3, 0, 10, 1, 4, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1009);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1010, 'Configurar pipeline CI/CD en OCI DevOps', 'Alta', 'Completado',
       DATE '2026-02-27', DATE '2026-03-04',
       'Configurar pipeline CI/CD en OCI DevOps.', 6, 7, 4, 0, 10, 1, 2, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1010);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1011, 'Crear bot de Telegram y registrar webhook', 'Media', 'Completado',
       DATE '2026-02-28', DATE '2026-03-03',
       'Crear bot de Telegram y registrar webhook.', 7, 5, 5, 0, 10, 1, 3, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1011);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1012, 'Configurar Dockerfile y build de imagenes del backend', 'Baja', 'Completado',
       DATE '2026-03-01', DATE '2026-03-04',
       'Configurar Dockerfile y build de imagenes del backend.', 8, 9, 6, 0, 10, 1, 4, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1012);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1013, 'Configurar cluster OKE para despliegue del backend', 'Alta', 'Completado',
       DATE '2026-03-02', DATE '2026-03-04',
       'Configurar cluster OKE para despliegue del backend.', 9, 8, 7, 0, 10, 1, 2, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1013);
COMMIT;

-- Sprint 1: Sprint 1 - Autenticacion y CRUD base
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1014, 'Implementar registro de usuarios (POST /auth/register)', 'Alta', 'Completado',
       DATE '2026-03-05', DATE '2026-03-08',
       'Implementar registro de usuarios (POST /auth/register).', 4, 2, 2, 0, 11, 1, 2, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1014);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1015, 'Implementar login con BCrypt (POST /auth/login)', 'Media', 'Completado',
       DATE '2026-03-06', DATE '2026-03-10',
       'Implementar login con BCrypt (POST /auth/login).', 5, 6, 3, 0, 11, 1, 3, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1015);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1016, 'CRUD de proyectos en el backend', 'Baja', 'Completado',
       DATE '2026-03-08', DATE '2026-03-13',
       'CRUD de proyectos en el backend.', 6, 5, 4, 0, 11, 1, 4, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1016);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1017, 'CRUD de sprints en el backend', 'Alta', 'Completado',
       DATE '2026-03-09', DATE '2026-03-15',
       'CRUD de sprints en el backend.', 7, 9, 5, 0, 11, 1, 2, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1017);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1018, 'CRUD de tareas en el backend', 'Media', 'Completado',
       DATE '2026-03-11', DATE '2026-03-18',
       'CRUD de tareas en el backend.', 8, 9, 6, 0, 11, 1, 3, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1018);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1019, 'Vista de login y registro en el portal React', 'Baja', 'Completado',
       DATE '2026-03-12', DATE '2026-03-15',
       'Vista de login y registro en el portal React.', 9, 7, 7, 0, 11, 1, 4, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1019);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1020, 'Vista de listado de proyectos en el portal', 'Alta', 'Completado',
       DATE '2026-03-14', DATE '2026-03-18',
       'Vista de listado de proyectos en el portal.', 10, 11, 8, 0, 11, 1, 2, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1020);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1021, 'Vista de tablero Kanban de tareas', 'Media', 'Completado',
       DATE '2026-03-15', DATE '2026-03-20',
       'Vista de tablero Kanban de tareas.', 4, 3, 2, 0, 11, 1, 3, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1021);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1022, 'Endpoint de listado de usuarios y roles', 'Baja', 'Completado',
       DATE '2026-03-17', DATE '2026-03-23',
       'Endpoint de listado de usuarios y roles.', 5, 7, 3, 0, 11, 1, 4, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1022);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1023, 'Comando /start del bot de Telegram', 'Alta', 'Completado',
       DATE '2026-03-18', DATE '2026-03-25',
       'Comando /start del bot de Telegram.', 6, 7, 4, 0, 11, 1, 2, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1023);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1024, 'Comando /tareas del bot de Telegram', 'Media', 'Completado',
       DATE '2026-03-20', DATE '2026-03-23',
       'Comando /tareas del bot de Telegram.', 7, 5, 5, 0, 11, 1, 3, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1024);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1025, 'Vincular cuenta de Telegram con usuario registrado', 'Baja', 'Completado',
       DATE '2026-03-21', DATE '2026-03-25',
       'Vincular cuenta de Telegram con usuario registrado.', 8, 9, 6, 0, 11, 1, 4, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1025);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1026, 'Pruebas unitarias de servicios CRUD', 'Alta', 'Completado',
       DATE '2026-03-23', DATE '2026-03-25',
       'Pruebas unitarias de servicios CRUD.', 9, 8, 7, 0, 11, 1, 2, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1026);
COMMIT;

-- Sprint 2: Sprint 2 - KPIs, historial y reportes
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1027, 'Modulo de KPIs: CRUD en el backend', 'Alta', 'Completado',
       DATE '2026-03-26', DATE '2026-03-29',
       'Modulo de KPIs: CRUD en el backend.', 4, 2, 2, 0, 12, 1, 2, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1027);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1028, 'Relacion TAREA_KPI y calculo de pesos por tarea', 'Media', 'Completado',
       DATE '2026-03-28', DATE '2026-04-01',
       'Relacion TAREA_KPI y calculo de pesos por tarea.', 5, 6, 3, 0, 12, 1, 3, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1028);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1029, 'Registro de historial de cambios de tareas (TAREA_HISTORIAL)', 'Baja', 'Completado',
       DATE '2026-03-30', DATE '2026-04-04',
       'Registro de historial de cambios de tareas (TAREA_HISTORIAL).', 6, 5, 4, 0, 12, 1, 4, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1029);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1030, 'Vista de dashboard de KPIs en el portal', 'Alta', 'Completado',
       DATE '2026-04-01', DATE '2026-04-07',
       'Vista de dashboard de KPIs en el portal.', 7, 9, 5, 0, 12, 1, 2, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1030);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1031, 'Grafica de burndown del sprint en el portal', 'Media', 'Completado',
       DATE '2026-04-03', DATE '2026-04-10',
       'Grafica de burndown del sprint en el portal.', 8, 9, 6, 0, 12, 1, 3, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1031);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1032, 'Notificaciones de tareas por vencer via Telegram', 'Baja', 'Completado',
       DATE '2026-04-05', DATE '2026-04-08',
       'Notificaciones de tareas por vencer via Telegram.', 9, 7, 7, 0, 12, 1, 4, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1032);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1033, 'Endpoint de reportes de avance por sprint', 'Alta', 'Completado',
       DATE '2026-04-07', DATE '2026-04-11',
       'Endpoint de reportes de avance por sprint.', 10, 11, 8, 0, 12, 1, 2, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1033);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1034, 'Filtros y busqueda de tareas en el portal', 'Media', 'Completado',
       DATE '2026-04-09', DATE '2026-04-14',
       'Filtros y busqueda de tareas en el portal.', 4, 3, 2, 0, 12, 1, 3, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1034);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1035, 'Vista de detalle de tarea con historial de cambios', 'Baja', 'Completado',
       DATE '2026-04-11', DATE '2026-04-17',
       'Vista de detalle de tarea con historial de cambios.', 5, 7, 3, 0, 12, 1, 4, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1035);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1036, 'Asignacion de tareas desde el bot de Telegram', 'Alta', 'Completado',
       DATE '2026-04-13', DATE '2026-04-20',
       'Asignacion de tareas desde el bot de Telegram.', 6, 7, 4, 0, 12, 1, 2, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1036);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1037, 'Exportar reporte de sprint a Excel/PDF', 'Media', 'Completado',
       DATE '2026-04-15', DATE '2026-04-18',
       'Exportar reporte de sprint a Excel/PDF.', 7, 5, 5, 0, 12, 1, 3, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1037);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1038, 'Mejoras de UI/UX del tablero Kanban', 'Baja', 'Completado',
       DATE '2026-04-17', DATE '2026-04-21',
       'Mejoras de UI/UX del tablero Kanban.', 8, 9, 6, 0, 12, 1, 4, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1038);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1039, 'Pruebas de integracion del modulo de KPIs', 'Alta', 'Completado',
       DATE '2026-04-19', DATE '2026-04-22',
       'Pruebas de integracion del modulo de KPIs.', 9, 8, 7, 0, 12, 1, 2, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1039);
COMMIT;

-- Sprint 3: Sprint 3 - IA, busqueda semantica y pruebas de carga
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1040, 'Cargar modelo ONNX ALL_MINILM_L12_V2 en Oracle 23ai', 'Alta', 'Completado',
       DATE '2026-04-23', DATE '2026-04-26',
       'Cargar modelo ONNX ALL_MINILM_L12_V2 en Oracle 23ai.', 4, 2, 2, 0, 13, 1, 2, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1040);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1041, 'Agregar columnas VECTOR e indices HNSW a las tablas principales', 'Media', 'Completado',
       DATE '2026-04-26', DATE '2026-04-30',
       'Agregar columnas VECTOR e indices HNSW a las tablas principales.', 5, 6, 3, 0, 13, 1, 3, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1041);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1042, 'Backfill de embeddings para datos existentes', 'Baja', 'Completado',
       DATE '2026-04-30', DATE '2026-05-05',
       'Backfill de embeddings para datos existentes.', 6, 5, 4, 0, 13, 1, 4, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1042);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1043, 'Implementar EmbeddingSyncService para sincronizar embeddings', 'Alta', 'Completado',
       DATE '2026-05-04', DATE '2026-05-10',
       'Implementar EmbeddingSyncService para sincronizar embeddings.', 7, 9, 5, 0, 13, 1, 2, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1043);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1044, 'Endpoint /rag/chat con busqueda semantica por proyecto', 'Media', 'Completado',
       DATE '2026-05-07', DATE '2026-05-14',
       'Endpoint /rag/chat con busqueda semantica por proyecto.', 8, 9, 6, 0, 13, 1, 3, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1044);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1045, 'Integracion con Groq (Llama 3.3) para generacion de respuestas', 'Baja', 'En Progreso',
       DATE '2026-05-11', DATE '2026-05-14',
       'Integracion con Groq (Llama 3.3) para generacion de respuestas.', 9, 8, 7, 0, 13, 1, 4, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1045);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1046, 'Vista de asistente de IA (chat) en el portal', 'Alta', 'En Progreso',
       DATE '2026-05-15', DATE '2026-05-19',
       'Vista de asistente de IA (chat) en el portal.', 10, 8, 8, 0, 13, 1, 2, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1046);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1047, 'Comando /preguntar del bot de Telegram para consultar a la IA', 'Media', 'En Progreso',
       DATE '2026-05-18', DATE '2026-05-23',
       'Comando /preguntar del bot de Telegram para consultar a la IA.', 4, 3, 2, 0, 13, 1, 3, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1047);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1048, 'Configurar pruebas de carga con JMeter (normal, pico, estres)', 'Baja', 'En Progreso',
       DATE '2026-05-22', DATE '2026-05-28',
       'Configurar pruebas de carga con JMeter (normal, pico, estres).', 5, 4, 3, 0, 13, 1, 4, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1048);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1049, 'Optimizar pool de conexiones para alta concurrencia', 'Alta', 'Pendiente',
       DATE '2026-05-26', DATE '2026-06-02',
       'Optimizar pool de conexiones para alta concurrencia.', 6, 0, 4, 0, 13, 1, 2, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1049);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1050, 'Revision de seguridad y manejo de credenciales sensibles', 'Media', 'Pendiente',
       DATE '2026-05-29', DATE '2026-06-01',
       'Revision de seguridad y manejo de credenciales sensibles.', 7, 0, 5, 0, 13, 1, 3, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1050);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1051, 'Configurar monitoreo y logging centralizado en OCI', 'Baja', 'Pendiente',
       DATE '2026-06-02', DATE '2026-06-06',
       'Configurar monitoreo y logging centralizado en OCI.', 8, 0, 6, 0, 13, 1, 4, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1051);
INSERT INTO ADMIN.TAREAS (TAREA_ID, NOMBRE, PRIORIDAD, ESTATUS, FECHA_CREACION, FECHA_VENCIMIENTO, DESCRIPCION, HORAS_ESTIMADAS, HORAS_REALES, STORY_POINTS, BORRADO, SPRINT_ID, PROYECTO_ID, ASIGNADO_A, CREADO_POR)
SELECT 1052, 'Documentacion final y preparacion de la demo', 'Alta', 'En Progreso',
       DATE '2026-06-06', DATE '2026-06-10',
       'Documentacion final y preparacion de la demo.', 9, 7, 7, 0, 13, 1, 2, 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ADMIN.TAREAS WHERE TAREA_ID = 1052);
COMMIT;

